variable "name" {
  type        = string
  description = "(Required) The name of the new API Destination. The name must be unique for your account. Maximum of 64 characters consisting of numbers, lower/upper case letters, .,-,_."
}
variable "description" {
  type        = string
  description = "(Optional) The description of the new API Destination. Maximum of 512 characters."
}
variable "invocation_endpoint" {
  type        = string
  description = " (Required) URL endpoint to invoke as a target. This could be a valid endpoint generated by a partner service. You can include wildcard as path parameters wildcards to be set from the Target HttpParameters."
}
variable "http_method" {
  type        = string
  description = "(Required) Select the HTTP method used for the invocation endpoint, such as GET, POST, PUT, etc."
}
variable "invocation_rate_limit_per_second" {
  type        = number
  default     = 300
  description = "(Optional) Enter the maximum number of invocations per second to allow for this destination. Enter a value greater than 0 (default 300)."
}
variable "connection_arn" {
  type        = string
  description = "(Required) ARN of the EventBridge Connection to use for the API Destination."
}