variable "name" {
    type        = string
    description = "(Optional) The friendly name for the SNS topic. By default generated by Terraform."
}

variable "display_name" {
    type        = string
    description = "(Optional) The display name for the SNS topic"
}

 variable "delivery_policy"  {
     type = string
     default = null
     description = "(Optional) The SNS delivery policy"
 }

variable "kms_master_key_id"    {
    type        = string
    default     = null
    description = "(Optional) The ID of an AWS-managed customer master key (CMK) for Amazon SNS or a custom CMK"
}

 variable "policy" {
     type = string
     default = null
     description = "(Optional) The fully-formed AWS policy as JSON"
  
 }

variable "tags" {
    type        = map(string)
    description = "List of resources TAGs"
}